Repository Breadcord/Breadcord, pull requests merged in 2023-09, with the labels that each got.

#129 Add lint action using ruff
  .github/workflows/lint.yml
  dev_requirements.txt
  pyproject.toml
Labels: enhancement

#144 Ruff fixes
  breadcord/app/app.py
  breadcord/app/screens/exception_modal.py
  breadcord/bot.py
  breadcord/config.py
  breadcord/core_modules/module_manager/__init__.py
  breadcord/core_modules/settings_manager/__init__.py
  breadcord/helpers.py
  breadcord/module.py
  pyproject.toml
Labels: improvement

#148 Allow specifying explicit paths as command line arguments
  breadcord/__main__.py
  breadcord/bot.py
Labels: enhancement

#150 Fix requirement install
  breadcord/module.py
Labels: bug

#151 Fix the linter screaming at the pydantic field_validators
  breadcord/module.py
Labels: bug

#149 [Snyk] Security upgrade pydantic from 2.3.0 to 2.4.0
  requirements.txt
Labels: dependencies
